# Generated by Django 4.2.24 on 2025-09-27 15:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=7)),
                ('niveau', models.CharField(max_length=4)),
                ('message', models.TextField()),
                ('resolue', models.IntegerField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'alerte',
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'categorie',
            },
        ),
        migrations.CreateModel(
            name='Dette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=150)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('date_dette', models.DateField()),
                ('produits_txt', models.TextField(blank=True, null=True)),
                ('remarques', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'dette',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantite', models.PositiveIntegerField(default=0)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('barcode', models.CharField(blank=True, max_length=128, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='inventaire.categorie')),
            ],
            options={
                'db_table': 'produit',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('mot_de_passe', models.CharField(max_length=128)),
                ('is_admin', models.IntegerField()),
            ],
            options={
                'db_table': 'utilisateur',
            },
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_vente', models.DateTimeField(auto_now_add=True)),
                ('user_name_snapshot', models.CharField(blank=True, max_length=150, null=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventaire.produit')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventaire.utilisateur')),
            ],
            options={
                'db_table': 'vente',
            },
        ),
        migrations.CreateModel(
            name='PaiementDette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('date_paiement', models.DateTimeField()),
                ('dette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaire.dette')),
            ],
            options={
                'db_table': 'paiement_dette',
            },
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(max_length=50)),
                ('utilisateur_email', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_action', models.DateTimeField()),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventaire.utilisateur')),
            ],
            options={
                'db_table': 'historique',
            },
        ),
        migrations.AddIndex(
            model_name='dette',
            index=models.Index(fields=['statut', 'date_dette'], name='ix_dette_statut_date'),
        ),
        migrations.AddIndex(
            model_name='dette',
            index=models.Index(fields=['date_dette'], name='ix_dette_date'),
        ),
        migrations.AddField(
            model_name='alerte',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventaire.produit'),
        ),
        migrations.AddIndex(
            model_name='vente',
            index=models.Index(fields=['produit', 'date_vente'], name='ix_vente_prod_date'),
        ),
        migrations.AddIndex(
            model_name='vente',
            index=models.Index(fields=['date_vente'], name='ix_vente_date'),
        ),
        migrations.AddIndex(
            model_name='vente',
            index=models.Index(fields=['utilisateur', 'date_vente'], name='ix_vente_user_date'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['nom'], name='ix_produit_nom'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['categorie'], name='ix_produit_categorie'),
        ),
        migrations.AddIndex(
            model_name='paiementdette',
            index=models.Index(fields=['dette'], name='ix_pay_dette'),
        ),
        migrations.AddIndex(
            model_name='historique',
            index=models.Index(fields=['date_action'], name='ix_historique_date'),
        ),
        migrations.AddIndex(
            model_name='alerte',
            index=models.Index(fields=['produit', 'created_at'], name='ix_alerte_prod_date'),
        ),
    ]
